// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShowHelpContext
{
    internal sealed partial class Vsix
    {
        public const string Id = "ShowHelpContext.8ddc4ea8-5de7-49ac-947d-4c50ff2854a1";
        public const string Name = "Show Help Context";
        public const string Description = @"Adds a tool window that shows the active help context. Can be used to troubleshoot extensions";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, help";
    }
}
